Use new pr-for-updates workflow with Github CLI
Signed-off-by: Nikita Skrynnik <nikita.skrynnik@xored.com>

diff --git a/.github/workflows/pr-for-updates.yaml b/.github/workflows/pr-for-updates.yaml
--- a/.github/workflows/pr-for-updates.yaml
+++ b/.github/workflows/pr-for-updates.yaml
@@ -10,16 +10,29 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
-      - name: Construct PR message
+      - name: Create a Pull Request
         run: |
-          PULL_REQUEST_BODY=$(git log --pretty='format:%B' -1 | sed '/^$/d;$d' | sed 's/#/# /g')
-          echo "$PULL_REQUEST_BODY"
-          echo "PULL_REQUEST_BODY<<EOF" >> $GITHUB_ENV
-          echo "$PULL_REQUEST_BODY" >> $GITHUB_ENV
-          echo "EOF" >> $GITHUB_ENV
-      - name: pull-request-action
-        uses: vsoch/pull-request-action@1.1.0
+          ref=${{ github.ref }}
+          branch=${ref#"refs/heads/"}
+
+          prTitle="Update from $branch"
+          prBody=$(git log --pretty='format:%B' -1 | sed '/^$/d;$d' | sed 's/#/# /g')
+
+          timeout_sec=3600
+          t0=$(date '+%s')
+          remaining=$(expr ${timeout_sec} + ${t0} - "$(date '+%s')")
+          while [[ ${remaining} -gt 0 ]]
+          do
+              echo "Starting command..."
+              if gh pr create -B "main" -H "$ref" --title "$prTitle" --body "$prBody" ; then
+                exit 0
+              else
+                sleep 30
+              fi
+              echo "Command has failed. Retry"
+              remaining=$(expr ${timeout_sec} + ${t0} - "$(date '+%s')")
+          done
+
+          exit 1
         env:
           GITHUB_TOKEN: ${{ secrets.NSM_BOT_GITHUB_TOKEN }}
-          BRANCH_PREFIX: "update/"
-          PULL_REQUEST_BRANCH: "main"
